### ISSUE TITLE
Change example for RG validation with NSStringMask

### ISSUE THREAD

**Issue by caiotomazelli** [fjcaetano/NSStringMask#11]
In your example at http://blog.flaviocaetano.com/post/nsstringmask/ you could change your RG example from this:
(\\d{2}).(\\d{3}).(\\d{3})-(\\d)

To that:
(\\d{2}).(\\d{3}).(\\d{3})-(\\d|[x|X])

In order to accept RGs which don't have a validation digit.

**Comment by fjcaetano** [comment]
Shouldn't it be `(\d{2}).(\d{3}).(\d{3})-(\d|x|X)`?

**Comment by caiotomazelli** [comment]
Yes, this is better :+1:

**Comment by fjcaetano** [comment]
Btw, your request is to edit the gist, right?

**Comment by caiotomazelli** [comment]
Yes, just the gist!

I loved the examples, but I found the border cases for rg and cpf validation are often mistread, so it would be nice to have a complete example! I think there would be changes to be made in order to contemplate cpf and rgs with less digits, but I have to work them out first.

**Comment by fjcaetano** [comment]
Feel free to fork the gist and update it as you wish.
