### ISSUE TITLE
Mask does not work with variable size

### ISSUE THREAD

**Issue by filipealva** [fjcaetano/NSStringMask#13]
Hello!

Congrats! This is the best mask lib I've found 👍 

I'm having a problem with this pattern: `(\\d{5,6})-(\\d{1})` 

It is supposed to always put the `-` char (if there are more than 1 char on the UITextField) but when I satisfy the first group of the pattern (i.e. when I input at least 5 characters) it removes the `-` char. 

I need something that works with ####-# and #####-#. It is never supposed to be like ##### (5 chars without spliting the last with the `-`).

I've tried to make it works but I can't until now u.u. Maybe for you it is clearer what we need to do to accomplish that. 

Can you help me, please? 

Thanks in advance!

**Comment by fjcaetano** [comment]
@filipealva the framework doesn't check for backwards compatibility.

Have you tried using two masks, one for 5 digits and another for 6 digits in the first group, and swapping them by checking the string length? I know it's not the optimal fix, but I believe it will work

**Comment by filipealva** [comment]
@fjcaetano thanks for answering! 

I ended up implementing the mask by myself with `UITextFieldDelegate` for this case.
