### ISSUE TITLE
Mask with static number at the beginning

### ISSUE THREAD

**Issue by fariza-z** [fjcaetano/NSStringMask#18]
I have an issue with the pattern, I'm trying to create phone number mask with static +7 at the beginning

My mask now looks like this
`"\\+(\\d{1}) \\((\\d{3})\\) (\\d{3}) (\\d{4})"`

what I want is to input static first digit
`"\\+7 \\((\\d{3})\\) (\\d{3}) (\\d{4})"`

However, it inputs 7 before every digit I dial on my numberpad keyboard. How can I solve this problem?

**Comment by fariza-z** [comment]
@fjcaetano I want textfield always have number 7 at the start, and the behavior is when I type 5 it puts 75 at the beginning^ which is right, but then when I type next digits what it does is - for example, typing next 4 it goes 7754, then 3 it goes 777543 and etc. at the end it just replaces all available characters in textfield and replaces it with 7s.

**Comment by fjcaetano** [comment]
@fariza-z The thing is that you need to specify a capture group which should only have one number 7, so your pattern should actually be this:

`\\+(7{1}) \\((\\d{3})\\) (\\d{3}) (\\d{4})`

Feel free to reopen the issue if it doesn't solve your situation.

**Comment by fariza-z** [comment]
@fjcaetano what you are suggesting doesn't quite solve my problem. As I said earlier, I want textfield to always have number 7 at the start. When user starts dialing his numbers, it should appear before entered digits.

In the pattern you are proposing it gets 7 as the only valid first digit user can input. In other words, it does noting when I dial anything but 7, that is not what I'm looking for.

**Comment by fjcaetano** [comment]
There's no way to do that because you're trying to match two characters, and the user can't input 2 chars at once.

With the solution I gave you, you can always setup the textfield so it starts with `+7` by default, but you won't be able to prevent the user from deleting the 7, however, even if they do so, they'll only be able to input 7 as the first digit anyway.
