### ISSUE TITLE
Problem when change Keyboard

### ISSUE THREAD

**Issue by diegommlima** [fjcaetano/NSStringMask#5]
Hello,
There is a "problem" in UITextField when you arrow the delegate as self. 
The bug happens when you try to switch keyboards, eg common Keyboard> Emoji Keyboard. 
It crashes the application. I thought of two solutions, the principle. Remove the delegate methods and treat all the "client" or create a view that will take UITextField and all its methods. And then what do you think? Any solution?

**Comment by fjcaetano** [comment]
Fechando por inatividade.
