### ISSUE TITLE
how can i get the original string in textfield?

### ISSUE THREAD

**Issue by carlosandresSanchez** [fjcaetano/NSStringMask#9]

**Comment by fjcaetano** [comment]
@carlosandresSanchez, what do you mean by "original string"? The cleaned string?

You can access the current value of the textfield normally as `textfield.text` or you may need something like `[textfield.mask validCharactersForString:textfield.text]`.

**Comment by fjcaetano** [comment]
Let me know if this works for you

**Comment by carlosandresSanchez** [comment]
what I need is the cleaned string. If with my masked string i Have 55 5555 5555, what I want is to get the string : "5555555555".

**Comment by fjcaetano** [comment]
Did you try using the `validCharactersForString:` method I described?

**Comment by carlosandresSanchez** [comment]
Yes, excuse. it works with the ```validCharactersForString: ``` method. 

Thank you so much!!

**Comment by fjcaetano** [comment]
Excellent!
